Let seichi-debug-gateway ditch private image
GiganticMinecraft/seichi_infra pull request #196
Opened 2022-03-29 20:36 UTC by kory33

[`seichi_bungee_dockers`](https://github.com/GiganticMinecraft/seichi_bungee_dockers) 周辺を全部こっちに引きずり出した

ひとまずデバッグ環境用のBungeeCordだけ。30行くらいのパッチで本番用のBungeeCordにも適用できそう。

2022-03-30 03:05 UTC, inductor commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bugneecord-plugins-config-patch.yaml
> +    synchronized-server-regex: "^(deb-s\\d+)$"
パワーを感じるわね

2022-03-30 03:07 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/configs/plugins/BungeeHubCommand-config.yml
> +already-connected-message: "You are already at the hub server!"
nit: 改行

2022-03-30 03:08 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/kustomization.yaml
> +configMapGenerator:
Good stuff

2022-03-30 04:07 UTC, kory33 commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/deployment.yaml
> +kind: Deployment
これ忘れてたんで直す

2022-03-30 04:11 UTC, kory33 commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/deployment.yaml
> +kind: Deployment
直した

2022-03-30 04:16 UTC, kory33 commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/statefulset.yaml
> +              values: 13068,221
おいｗ

2022-03-30 04:21 UTC, kory33 commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-jsonpatch.yaml
> +    - deb-s1
そういえばこれ雑に書いたけど JSON Patch がYAMLオブジェクト受け付けてくれるのかよく知らない

2022-03-30 04:23 UTC, kory33 commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/configs/plugins/SwiftMOTD-config.yml
> +    - '&b&lseichi.click network &6&l| &7&lver &a&l1.12.2 , 1.14.4%newline&fYou have a pickaxe. You have a time. Oh! Seichi Love.'
どうせKustomizeするしこれ消して良さそう

2022-03-30 05:56 UTC, inductor requested changes

2022-03-30 05:56 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/kustomization.yaml
> +  - "./deployment.yaml"
```suggestion
  - "./statefulset.yaml"
```

2022-03-30 06:00 UTC, kory33 commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/kustomization.yaml
> +  - "./deployment.yaml"
正しい

2022-03-30 06:03 UTC, inductor requested changes

2022-03-30 06:03 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/kustomization.yaml
> +      - config.yml=configs/bungeecord-config.yml
```suggestion
      - config.yml=configs/bungeecord-config.yaml
```

2022-03-30 06:03 UTC, inductor commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/kustomization.yaml
> +  - "bungeecord-plugins-config-patch.yaml"
```
- bungeecord-plugins-config-patch.yaml
`: evalsymlink failure on '/home/kela/go/src/github.com/GiganticMinecraft/seichi_infra/proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-plugins-config-patch.yaml' : lstat /home/kela/go/src/github.com/GiganticMinecraft/seichi_infra/proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-plugins-config-patch.yaml: no such file or directory
```

2022-03-30 06:14 UTC, kory33 commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/kustomization.yaml
> +  - "bungeecord-plugins-config-patch.yaml"
しょーもなさすぎて笑ってしまった

2022-03-30 08:49 UTC, inductor requested changes
Fix configmap format

ref. https://kubernetes.io/docs/tasks/configure-pod-container/configure-pod-configmap/

2022-03-30 08:49 UTC, inductor commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
> +  config.yml:
```suggestion
  config.yml: |
```

2022-03-30 08:49 UTC, inductor commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-plugin-configs-patch.yaml
> +  SwiftMOTD/config.yml:
```suggestion
  BungeeHubCommand/config.yml: |
    hub-server-name: "deb-s1"
  BungeeKick/config.yml: |
    ServerName: "deb-s1"
  BungeeSemaphore/config.yml: |
    synchronized-server-regex: "^(deb-s\\d+)$"
  SwiftMOTD/config.yml: |
```

2022-03-30 08:49 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/configs/bungeecord-config.yaml
> +  config.yml:
```suggestion
  config.yml: |
```

2022-03-30 08:49 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/configs/plugin-configs.yaml
> +  SwiftMOTD/config.yml:
```suggestion
  BungeeHubCommand/config.yml: |
    # https://github.com/GiganticMinecraft/BungeeHubCommand/blob/a33b73f258de7d484fa961d000921275fb51c45b/src/main/resources/config.yml
    # Needs override.
    # Provide name of the server to which players are sent when executing the "hub" command
    hub-server-name:

    # The message to be shown when a player already connected to the hub server tryed to run the "hub" command.
    already-connected-message: "You are already at the hub server!"

  BungeeKick/config.yml: |
    # Needs override.
    # This is where the player is kicked to. This is usually the lobby/hub server
    ServerName:

    # Message to be sent to the player who has been kicked. This message is followed by the kick reason
    KickMessage: '&6You have been kicked! Reason:&4 '

    # Set this to True if you want the kicked player to be able to see the kick reason.
    ShowKickMessage: True

  BungeeSemaphore/config.yml: |
    # Needs override.
    # Provide a regex to match servers that needs a semaphore guard.
    synchronized-server-regex:

    redis:
      host: cloudflared-redis--bungeesemaphore
      port: 6379

    locale:
      error:
        failed-saving-data: "Spigotサーバーがデータの保存に失敗しました！"

    timeout:
      # Timeout for locking out players from servers when downstream saves are not confirmed.
      # Once this duration passes, a locked out player is able to join the target downstream server.
      # Default is 60 seconds timeout. Specify negative values to disable timeouts.
      millis: 4000

  RedisBungee/config.yml: |
    # RedisBungee configuration file.
    # PLEASE READ THE WIKI: https://github.com/minecrafter/RedisBungee/wiki

    # An identifier for this BungeeCord instance.
    # NOTE:
    #   This field must be unique among multiple BungeeCord instances
    #     that connect to the redis instance.
    #   In k8s context, substituting a HOSTNAME (name of the pod) here solves the issue.
    #
    #   In fact, itzg/bungeecord can expand environment variable references as long as
    #     configs are placed in /config/plugins/RedisBungee directory.
    #   See https://github.com/itzg/docker-bungeecord/tree/9113d93882d1945d5469141b77eb922233842be9#replacing-variables-inside-configs
    #     for more details.
    server-id: ${HOSTNAME}

    redis-server: cloudflared-redis--redisbungee
    redis-port: 6379
    # OPTIONAL: If your Redis server uses AUTH, set the password required.
    redis-password: ""

    # Maximum connections that will be maintained to the Redis server.
    # The default is 8. This setting should be left as-is unless you have some wildly
    # inefficient plugins or a lot of players.
    max-redis-connections: 8

    # Whether or not RedisBungee should install its version of regular BungeeCord commands.
    # Often, the RedisBungee commands are desired, but in some cases someone may wish to
    # override the commands using another plugin.
    #
    # If you are just denying access to the commands, RedisBungee uses the default BungeeCord
    # permissions - just deny them and access will be denied.
    #
    # Please note that with build 787+, most commands overridden by RedisBungee were moved to
    # modules, and these must be disabled or overridden yourself.
    register-bungee-commands: true

    # A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
    # restart scripts.
    exempt-ip-addresses: []

  SwiftMOTD/config.yml: |
```

2022-03-30 08:49 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/configs/plugin-configs.yaml
> +  SwiftMOTD/config.yml:
```suggestion
  BungeeHubCommand/config.yml: |
    # https://github.com/GiganticMinecraft/BungeeHubCommand/blob/a33b73f258de7d484fa961d000921275fb51c45b/src/main/resources/config.yml
    # Needs override.
    # Provide name of the server to which players are sent when executing the "hub" command
    hub-server-name:

    # The message to be shown when a player already connected to the hub server tryed to run the "hub" command.
    already-connected-message: "You are already at the hub server!"

  BungeeKick/config.yml: |
    # Needs override.
    # This is where the player is kicked to. This is usually the lobby/hub server
    ServerName:

    # Message to be sent to the player who has been kicked. This message is followed by the kick reason
    KickMessage: '&6You have been kicked! Reason:&4 '

    # Set this to True if you want the kicked player to be able to see the kick reason.
    ShowKickMessage: True

  BungeeSemaphore/config.yml: |
    # Needs override.
    # Provide a regex to match servers that needs a semaphore guard.
    synchronized-server-regex:

    redis:
      host: cloudflared-redis--bungeesemaphore
      port: 6379

    locale:
      error:
        failed-saving-data: "Spigotサーバーがデータの保存に失敗しました！"

    timeout:
      # Timeout for locking out players from servers when downstream saves are not confirmed.
      # Once this duration passes, a locked out player is able to join the target downstream server.
      # Default is 60 seconds timeout. Specify negative values to disable timeouts.
      millis: 4000

  RedisBungee/config.yml: |
    # RedisBungee configuration file.
    # PLEASE READ THE WIKI: https://github.com/minecrafter/RedisBungee/wiki

    # An identifier for this BungeeCord instance.
    # NOTE:
    #   This field must be unique among multiple BungeeCord instances
    #     that connect to the redis instance.
    #   In k8s context, substituting a HOSTNAME (name of the pod) here solves the issue.
    #
    #   In fact, itzg/bungeecord can expand environment variable references as long as
    #     configs are placed in /config/plugins/RedisBungee directory.
    #   See https://github.com/itzg/docker-bungeecord/tree/9113d93882d1945d5469141b77eb922233842be9#replacing-variables-inside-configs
    #     for more details.
    server-id: ${HOSTNAME}

    redis-server: cloudflared-redis--redisbungee
    redis-port: 6379
    # OPTIONAL: If your Redis server uses AUTH, set the password required.
    redis-password: ""

    # Maximum connections that will be maintained to the Redis server.
    # The default is 8. This setting should be left as-is unless you have some wildly
    # inefficient plugins or a lot of players.
    max-redis-connections: 8

    # Whether or not RedisBungee should install its version of regular BungeeCord commands.
    # Often, the RedisBungee commands are desired, but in some cases someone may wish to
    # override the commands using another plugin.
    #
    # If you are just denying access to the commands, RedisBungee uses the default BungeeCord
    # permissions - just deny them and access will be denied.
    #
    # Please note that with build 787+, most commands overridden by RedisBungee were moved to
    # modules, and these must be disabled or overridden yourself.
    register-bungee-commands: true

    # A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
    # restart scripts.
    exempt-ip-addresses: []

  SwiftMOTD/config.yml: |
```

2022-03-30 08:49 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/configs/plugin-configs.yaml
> +  SwiftMOTD/config.yml:
```suggestion
  BungeeHubCommand/config.yml: |
    # https://github.com/GiganticMinecraft/BungeeHubCommand/blob/a33b73f258de7d484fa961d000921275fb51c45b/src/main/resources/config.yml
    # Needs override.
    # Provide name of the server to which players are sent when executing the "hub" command
    hub-server-name:

    # The message to be shown when a player already connected to the hub server tryed to run the "hub" command.
    already-connected-message: "You are already at the hub server!"

  BungeeKick/config.yml: |
    # Needs override.
    # This is where the player is kicked to. This is usually the lobby/hub server
    ServerName:

    # Message to be sent to the player who has been kicked. This message is followed by the kick reason
    KickMessage: '&6You have been kicked! Reason:&4 '

    # Set this to True if you want the kicked player to be able to see the kick reason.
    ShowKickMessage: True

  BungeeSemaphore/config.yml: |
    # Needs override.
    # Provide a regex to match servers that needs a semaphore guard.
    synchronized-server-regex:

    redis:
      host: cloudflared-redis--bungeesemaphore
      port: 6379

    locale:
      error:
        failed-saving-data: "Spigotサーバーがデータの保存に失敗しました！"

    timeout:
      # Timeout for locking out players from servers when downstream saves are not confirmed.
      # Once this duration passes, a locked out player is able to join the target downstream server.
      # Default is 60 seconds timeout. Specify negative values to disable timeouts.
      millis: 4000

  RedisBungee/config.yml: |
    # RedisBungee configuration file.
    # PLEASE READ THE WIKI: https://github.com/minecrafter/RedisBungee/wiki

    # An identifier for this BungeeCord instance.
    # NOTE:
    #   This field must be unique among multiple BungeeCord instances
    #     that connect to the redis instance.
    #   In k8s context, substituting a HOSTNAME (name of the pod) here solves the issue.
    #
    #   In fact, itzg/bungeecord can expand environment variable references as long as
    #     configs are placed in /config/plugins/RedisBungee directory.
    #   See https://github.com/itzg/docker-bungeecord/tree/9113d93882d1945d5469141b77eb922233842be9#replacing-variables-inside-configs
    #     for more details.
    server-id: ${HOSTNAME}

    redis-server: cloudflared-redis--redisbungee
    redis-port: 6379
    # OPTIONAL: If your Redis server uses AUTH, set the password required.
    redis-password: ""

    # Maximum connections that will be maintained to the Redis server.
    # The default is 8. This setting should be left as-is unless you have some wildly
    # inefficient plugins or a lot of players.
    max-redis-connections: 8

    # Whether or not RedisBungee should install its version of regular BungeeCord commands.
    # Often, the RedisBungee commands are desired, but in some cases someone may wish to
    # override the commands using another plugin.
    #
    # If you are just denying access to the commands, RedisBungee uses the default BungeeCord
    # permissions - just deny them and access will be denied.
    #
    # Please note that with build 787+, most commands overridden by RedisBungee were moved to
    # modules, and these must be disabled or overridden yourself.
    register-bungee-commands: true

    # A list of IP addresses for which RedisBungee will not modify the response for, useful for automatic
    # restart scripts.
    exempt-ip-addresses: []

  SwiftMOTD/config.yml: |
```

2022-03-30 08:49 UTC, inductor commented on proxy-kubernetes/kustomize-bases/minecraft-gateway-bungeecord-without-private-image/configs/plugin-configs.yaml
> +  SwiftMOTD/config.yml:
なんか多分量が多すぎて一度に送れなかったんだけどここも。

2022-03-30 08:54 UTC, kory33 commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
> +  config.yml:
エ、これでpatchできるんですか？

2022-03-30 08:54 UTC, kory33 commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
> +  config.yml:
(電車乗ったらdoc読んできます)

2022-03-30 09:07 UTC, inductor commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
> +  config.yml:
あーpatchか。。。

でもこうしないとkustomize build失敗すると思うんだよな

2022-03-30 09:19 UTC, kory33 commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
> +  config.yml:
ん、最新revisionの時点で kustomize build は通るはずです

2022-03-30 09:21 UTC, inductor commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
> +  config.yml:
あ。ごめん。buildじゃないや。Diffでエラーになってた

```
$ kubectl diff -k proxy-kubernetes/apps/seichi-debug-gateway/bungeecord
Error from server (BadRequest): ConfigMap in version "v1" cannot be handled as a ConfigMap: v1.ConfigMap.Data: ReadString: expects " or n, but found {, error found in #10 byte of ...|fig.yml":{"always_ha|..., bigger context ...|{"apiVersion":"v1","data":{"config.yml":{"always_handle_packets":false,"connection_throttle|...
```

2022-03-30 09:25 UTC, inductor commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
> +  config.yml:
https://github.com/kubernetes-sigs/kustomize/issues/2962 ここらへんかな

2022-03-30 09:34 UTC, kory33 commented on proxy-kubernetes/apps/seichi-debug-gateway/bungeecord/bungeecord-config-patch.yaml
> +  config.yml:
ンンンンｗｗｗｗ
generator pluginは渋いな…

2022-04-01 07:22 UTC, inductor approved these changes

2022-04-01 07:22 UTC, merged