feat: logdna-agentと動作に必要なsecretを追加
GiganticMinecraft/seichi_infra pull request #250
Opened 2022-04-18 05:24 UTC by unchama

[LogDNA](https://www.logdna.com) でコンテナログを閲覧可能にする
※terraform側にWorkspace variables`lke_k8s_logdna_agent_ingestion_key`の追加を別途実施済

変なところあれば教えてくださいm(_ _)m

2022-04-18 09:10 UTC, kory33 commented on proxy-kubernetes/apps/cluster-wide-app-resources/logdna-agent.yaml
> +            key: INGESTION_KEY
1. これをここに書いて動くのか怪しい(このように書いているexampleが見当たらなかった)
2. `cluster-wide-apps/logdna-agent-ingestion-key` が更新された時にreloadが走らない

等の問題はありそうです。どちらも解決する手段を見つけられなかったのでう～んという感じですね(1に関してはとりあえずマージしてみても良さそうではある)

2022-04-19 02:58 UTC, inductor requested changes

2022-04-19 02:58 UTC, inductor commented on proxy-kubernetes/apps/cluster-wide-app-resources/logdna-agent.yaml
> +            key: INGESTION_KEY
https://github.com/logdna/logdna-agent-v2#configuration

`LOGDNA_INGESTION_KEY` じゃないの？

2022-04-19 03:11 UTC, kory33 submitted a review, later dismissed
@inductor 直すべきはたぶんこっち

2022-04-19 03:11 UTC, kory33 commented on terraform/lke_cluster_secrets.tf
> +    TUNNEL_CREDENTIAL = var.lke_k8s_logdna_agent_ingestion_key
```suggestion
    INGESTION_KEY = var.lke_k8s_logdna_agent_ingestion_key
```

2022-04-19 03:14 UTC, kory33 commented on proxy-kubernetes/apps/cluster-wide-app-resources/logdna-agent.yaml
> +            key: INGESTION_KEY
ここで意図されてるのはlogdna側の設定キーではなくてSecret(のdata)内のパス参照ですかね(なので先程のレビューで直すべき箇所を指摘しました)
ただargocdのhelm ApplicationにvaluesFromと書けるかが怪しいという指摘が元のやつです(こう書いてるsample見当たらなかったので)

2022-04-19 03:31 UTC, inductor commented on terraform/lke_cluster_secrets.tf
> +    TUNNEL_CREDENTIAL = var.lke_k8s_logdna_agent_ingestion_key
両方でしょ

2022-04-19 03:33 UTC, inductor commented on proxy-kubernetes/apps/cluster-wide-app-resources/logdna-agent.yaml
> +            key: INGESTION_KEY
ああ、そうだねこれをvaluesFromは普通におかしいわ。

2022-04-19 03:53 UTC, kory33 commented on proxy-kubernetes/apps/cluster-wide-app-resources/logdna-agent.yaml
> +            key: INGESTION_KEY
それはそうとしてこのHelmイメージGitOps運用をどう想定してるんだになってる ArgoCDのHelmイメージとかは `$secret:key` で参照できるようになってますが、これの INGESTION_KEY は直書き以外でどう値を注入すればいいんでしょう

2022-04-21 18:01 UTC, kory33 commented on terraform/lke_cluster_secrets.tf
> +    TUNNEL_CREDENTIAL = var.lke_k8s_logdna_agent_ingestion_key
secretの値の参照まで `LOGDNA_INGESTION_KEY` になっている必要は無いですので

2022-04-21 20:37 UTC, kory33 commented
このHelm Chartドキュメントがちょっと微妙くて、`updateOnSecretChange` みたいなオプションはあるのにどのsecretのどのノードに値セットすればいいかみたいなのが書かれていないので、Kustomizationのresources指定で直接manifestを引っ張ってくるのが良さそうという感じになっています

2022-04-22 16:01 UTC, kory33 commented
@unchama#3551 @inductor#5052 
namespaceは既存のやつ使うんで、 `agent-resources.yaml` だけ入れてreloader設定だけパッチするようにしました

2022-04-23 03:10 UTC, inductor approved these changes

2022-04-23 10:49 UTC, merged