Deploy kubernetes-cluster to seichi-onp-network
GiganticMinecraft/seichi_infra pull request #264
Opened 2022-05-11 16:03 UTC by unchama

- [ ] Draftを脱する前にスクリプトダウンロード元のブランチ名を`main`に書き換えること

2022-05-11 17:21 UTC, kory33 commented
@unchama (ready for review前にshellcheckの指摘は全部直す(無理なやつはignoreする)のお願いします)

2022-05-11 22:36 UTC, unchama commented
> @unchama (ready for review前にshellcheckの指摘は全部直す(無理なやつはignoreする)のお願いします)

OKデス！

2022-05-12 06:20 UTC, inductor requested changes

2022-05-12 06:20 UTC, inductor commented on seichi-onp-k8s/scripts/k8s-node-setup.sh
> +#/bin/bash -eu
```suggestion
#!/usr/bin/env bash -eu
```

2022-05-13 06:16 UTC, unchama commented on seichi-onp-k8s/scripts/k8s-node-setup.sh
> +sudo containerd config default > /etc/containerd/config.toml
```suggestion
sudo containerd config default | sudo tee /etc/containerd/config.toml > /dev/null
```

2022-05-13 08:17 UTC, KisaragiEffective reviewed
nits

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +# 前提条件
```suggestion
## 前提条件
```

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +# クラスタ操作
```suggestion
## クラスタ操作
```

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +# 作成フロー
```suggestion
## 作成フロー
```

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +```
```suggestion
```sh
```

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +```
```suggestion
```sh
```

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +```
```suggestion
```sh
```

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +```
```suggestion
```sh
```

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +```
```suggestion
```sh
```

2022-05-13 08:17 UTC, KisaragiEffective commented on seichi-onp-k8s/README.md
> +# cleanup
```suggestion
## cleanup
```

2022-05-14 06:33 UTC, inductor requested changes

2022-05-14 06:33 UTC, inductor commented on seichi-onp-k8s/scripts/k8s-node-setup.sh
> +helm install metallb metallb/metallb -f "$HOME"/metallb_values.yaml
namespaceが指定されてない。

何ならこれはHelm使わなくてもいい気がするけどHelmがいい理由があれば知りたい。

https://github.com/inductor/home-k8s-lab/tree/main/manifests/metallb みたいにYAMLを持ってそれをArgo CDのApplicationに含めるのがいいと思う。

2022-05-16 03:37 UTC, kory33 commented on seichi-onp-k8s/README.md
> +オンプレミス上に整地鯖用のkubernetesクラスタをデプロイする為のスクリプト群です。
デプロイ用スクリプト群としてのみ機能するディレクトリにはならなさそう(例えば、オンプレk8sクラスタ上に乗っけるアプリケーションの定義とかも含めそう)なので、この説明は不適かもです

2022-05-16 03:41 UTC, kory33 commented on seichi-onp-k8s/README.md
> +オンプレミス上に整地鯖用のkubernetesクラスタをデプロイする為のスクリプト群です。
これ、なんならクラスタ自体の構成を管理するサブディレクトリと、クラスタの上で動くアプリケーション群を管理するサブディレクトリを seichi-onp-k8s 下の同階層に置いて完全に分けていいのでは、と思ってきたんですけど、どう思われますか？ @inductor @unchama

2022-05-17 02:10 UTC, inductor commented on seichi-onp-k8s/README.md
> +オンプレミス上に整地鯖用のkubernetesクラスタをデプロイする為のスクリプト群です。
いいとおもいます

2022-05-17 02:28 UTC, inductor requested changes

2022-05-17 02:28 UTC, inductor commented on seichi-onp-k8s/scripts/k8s-node-setup.sh
> +kubeadm init --config "$HOME"/init_kubeadm.yaml --skip-phases=addon/kube-proxy --ignore-preflight-errors=NumCPU,Mem
```suggestion
kubeadm init --config "$HOME"/init_kubeadm.yaml --skip-phases=addon/kube-proxy --upload-certs --ignore-preflight-errors=NumCPU,Mem
```

2022-05-17 03:21 UTC, inductor requested changes

2022-05-17 03:21 UTC, inductor commented on seichi-onp-k8s/deploy-vm.sh
> +#!/bin/bash
```suggestion
#!/usr/bin/env bash
```

2022-05-17 12:40 UTC, inductor commented on seichi-onp-k8s/scripts/k8s-node-setup.sh
> +controlPlaneEndpoint: "${KUBE_API_SERVER_VIP}:8443"
多分こういうのが必要

```suggestion
controlPlaneEndpoint: "${KUBE_API_SERVER_VIP}:8443"
apiServer:
  certSANs:
  - "k8s-api.onp-k8s.admin.seichi.click"
```

2022-05-17 15:51 UTC, kory33 commented
@unchama ちなみに ignore というのは mark as resolved するという事ではなくて、[shellcheck へのディレクティブで ignore する](https://github.com/koalaman/shellcheck/wiki/Directive)ということです

[SC2206](https://github.com/koalaman/shellcheck/wiki/SC2206) は直せるんで直しましょう

2022-05-17 19:12 UTC, unchama commented
動作確認できたのでready for reviewです！ @inductor @kory33

2022-05-20 13:26 UTC, inductor approved these changes

2022-05-20 13:26 UTC, merged