オンプレクラスタ周りのドキュメントの推敲
GiganticMinecraft/seichi_infra pull request #289
Opened 2022-05-23 16:52 UTC by kory33

2022-05-23 21:03 UTC, kory33 commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +オンプレ環境の内部ネットワーク内からクラスタを操作する場合、各環境のHAProxyに持たせた k8s API Endpoint の VIP に接続することができます。
> 各環境の

と原文にあったんですけど、これどういうことですか？各CPノードってそれぞれAPIのVIP持ってるんですか？

2022-05-23 21:51 UTC, inductor commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +オンプレ環境の内部ネットワーク内からクラスタを操作する場合、各環境のHAProxyに持たせた k8s API Endpoint の VIP に接続することができます。
検証用と本番用という意味。
セグメントごとに1つ。

2022-05-23 21:52 UTC, inductor commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +Container Network Interface には Cilium を利用しています。
```suggestion
CNI には Cilium を利用しています。
```

2022-05-23 21:54 UTC, kory33 commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +オンプレ環境の内部ネットワーク内からクラスタを操作する場合、各環境のHAProxyに持たせた k8s API Endpoint の VIP に接続することができます。
アーその単位か　初見でわかんないので書き足します

2022-05-23 21:54 UTC, inductor commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +    `known_hosts` の登録を削除する必要がある理由は、VMを作り直す度にホストの公開鍵が変わる為です。
```suggestion
    `known_hosts` の登録を削除する必要がある理由は、VMを作り直す度にホストの公開鍵が変わるためです。
```

http://blog.livedoor.jp/ddrerizayoi/archives/33076063.html

2022-05-23 21:58 UTC, inductor requested changes

2022-05-23 21:58 UTC, inductor commented on seichi-onp-k8s/cluster-boot-scripts/README.md
>  オンプレミス上に整地鯖用のKubernetesクラスタをデプロイする為のスクリプト群です。
```suggestion
オンプレミス上に整地鯖用のKubernetesクラスタをデプロイするためのスクリプト群です。
```

スコープ外だけど統一しよう

理由はditto

2022-05-23 21:58 UTC, inductor commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +        # known_hosts登録削除(VM作り直す度にホスト公開鍵が変わる為)
```suggestion
        # known_hosts登録削除(VM作り直す度にホスト公開鍵が変わるため)
```

2022-05-23 21:58 UTC, inductor commented on seichi-onp-k8s/cluster-boot-scripts/README.md
>  - proxmoxのホストコンソール上で以下コマンド実行。ノードローカルにいるVMしか操作できない為、全てのノードで打って回る。
```suggestion
- proxmoxのホストコンソール上で以下コマンド実行。ノードローカルにいるVMしか操作できないため、全てのノードで打って回る。
```
ditto

2022-05-23 22:01 UTC, kory33 commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +    `known_hosts` の登録を削除する必要がある理由は、VMを作り直す度にホストの公開鍵が変わる為です。
そうなんだ　今日の知見です

2022-05-23 22:09 UTC, inductor commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +2022/05/23現在、クラスタは (3 control plane nodes + 3 worker nodes) の構成で[作成されています](https://github.com/GiganticMinecraft/seichi_infra/blob/9b6a9346371b8f2add3a786b6badbe4e13d4464c/seichi-onp-k8s/cluster-boot-
このblobがbranchではなくcommit hashのリンクなのはあえてそうしている？

2022-05-23 22:09 UTC, inductor commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> + - まず、クラスタのセットアップスクリプトにより、`k8s-api.onp-k8s.admin.local-tunnels.seichi.click` がクラスタAPIのSSL証明書のSAN(Subject Alternative Name)に追記されており、かつ、このドメイン(`k8s-api.onp-k8s.admin.local-tunnels.seichi.click`) は `127
ここ図があったほうがわかりやすそう（こなみかん）

このPRのスコープでなくともよいです

2022-05-23 22:10 UTC, kory33 commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> +2022/05/23現在、クラスタは (3 control plane nodes + 3 worker nodes) の構成で[作成されています](https://github.com/GiganticMinecraft/seichi_infra/blob/9b6a9346371b8f2add3a786b6badbe4e13d4464c/seichi-onp-k8s/cluster-boot-
はい、行番号指定はbranch指定だとズレがちなので、sha指定したうえで「2022/05/23現在」と言及し、possibly outdatedだよ、でも元のデータはここだよ、というポインタを書いています

2022-05-23 22:10 UTC, kory33 commented on seichi-onp-k8s/cluster-boot-scripts/README.md
> + - まず、クラスタのセットアップスクリプトにより、`k8s-api.onp-k8s.admin.local-tunnels.seichi.click` がクラスタAPIのSSL証明書のSAN(Subject Alternative Name)に追記されており、かつ、このドメイン(`k8s-api.onp-k8s.admin.local-tunnels.seichi.click`) は `127
わかるなぁ　書きます

2022-05-23 22:42 UTC, inductor commented
うんちゃま見て

2022-05-23 23:28 UTC, unchama commented
ざっと見ました。内容はOKです。リポジトリルートのREADME.mdからのリンクは貼りますか？

2022-05-24 00:20 UTC, kory33 commented
> ざっと見ました。内容はOKです。リポジトリルートのREADME.mdからのリンクは貼りますか？

張りました

2022-05-24 00:33 UTC, hpe-ota-kohei approved these changes

2022-05-24 00:33 UTC, inductor approved these changes

2022-05-24 00:33 UTC, inductor commented
アカウント間違えて草（影響ないけど）

2022-05-24 00:33 UTC, merged

2022-05-24 01:41 UTC, kory33 commented
図足した #290