feat: vm-diskはローカルでホストする
GiganticMinecraft/seichi_infra pull request #425
Opened 2022-06-04 03:10 UTC by unchama

SAN Segment経由でホストしている共有ストレージだとcontrol-plane上にいるetcdのパフォーマンスが低下したのでローカルディスクにお引越しする

2022-06-04 03:38 UTC, inductor requested changes

2022-06-04 03:38 UTC, inductor commented on seichi-onp-k8s/cluster-boot-up/scripts/proxmox-host-terminal/deploy-vm.sh
> +ssh 192.168.16.153 qm move-disk 1103 scsi0 local-lvm --delete true
moveじゃなくて作成の段階でlocal diskを使うようにしてください

2022-06-04 03:39 UTC, unchama commented on seichi-onp-k8s/cluster-boot-up/scripts/proxmox-host-terminal/deploy-vm.sh
> +ssh 192.168.16.153 qm move-disk 1103 scsi0 local-lvm --delete true
OKdesu

2022-06-04 03:44 UTC, unchama commented on seichi-onp-k8s/cluster-boot-up/scripts/proxmox-host-terminal/deploy-vm.sh
> +ssh 192.168.16.153 qm move-disk 1103 scsi0 local-lvm --delete true
検証環境でコマンドの有効性確認してからready for reviewにする

2022-06-13 23:33 UTC, unchama commented
- clone時点だとローカルディスクを指定できないのでclone後のmove-diskは必須っぽい
- 冗長な部分をリファクタしました

2022-06-15 03:13 UTC, inductor approved these changes

2022-06-15 03:13 UTC, merged