feat: add newrelic agents
GiganticMinecraft/seichi_infra pull request #911
Opened 2023-03-11 12:19 UTC by unchama

よくわからんのでとりあえずk8s integrationのinstall wizardをデフォルト値で進めたら出てきたhelm installコマンドをベースに錬成。

追加オプションは以下がデフォルト選択

- [x] Scrape Prometheus endpoints
  - [ ] Scrape all Prometheus endpoints
  - [x] Scrape all endpoints except Kubernetes infrastructure endpoints already collected by the Kubernetes integration (recommended)
  - [ ] Scrape only endpoints with curated experiences
- [ ] Gather Log data
- [x] Instant service-level insights, full-body requests, and application profiles through Pixie
Pixie uses eBPF to automatically detect any HTTP-based services in this cluster and gather data. For even deeper insights, you can add language agents to individual services.
- [ ] Pixie is already running in this cluster

install wizardで出たベースとなったコマンドはこんな感じ

```bash
function ver { printf "%03d%03d" $(echo "$1" | tr '.' ' '); } && \
K8S_VERSION=$(kubectl version --short 2>&1 | grep 'Server Version' | awk -F' v' '{ print $2; }' | awk -F. '{ print $1"."$2; }') && \
if [[ $(ver $K8S_VERSION) -lt $(ver "1.25") ]]; then KSM_IMAGE_VERSION="v2.6.0"; else KSM_IMAGE_VERSION="v2.7.0"; fi && \
helm repo add newrelic https://helm-charts.newrelic.com && helm repo update && \
kubectl create namespace newrelic ; helm upgrade --install newrelic-bundle newrelic/nri-bundle \
 --set global.licenseKey=***sensored*** \
 --set global.cluster=seichi-onp-k8s \
 --namespace=newrelic \
 --set newrelic-infrastructure.privileged=true \
 --set global.lowDataMode=true \
 --set kube-state-metrics.image.tag=${KSM_IMAGE_VERSION} \
 --set kube-state-metrics.enabled=true \
 --set kubeEvents.enabled=true \
 --set newrelic-prometheus-agent.enabled=true \
 --set newrelic-prometheus-agent.lowDataMode=true \
 --set newrelic-prometheus-agent.config.kubernetes.integrations_filter.enabled=false \
 --set newrelic-pixie.enabled=true \
 --set newrelic-pixie.apiKey=***sensored*** \
 --set pixie-chart.enabled=true \
 --set pixie-chart.deployKey=***sensored*** \
 --set pixie-chart.clusterName=seichi-onp-k8s  
```

2023-03-12 23:59 UTC, inductor commented on terraform/onp_cluster_secrets.tf
> +    "deploy-key"  = var.newrelic_pixie_chart_deploy_key
命名規則の統一性が。。。

2023-03-12 23:59 UTC, inductor requested changes
命名規則だけなんとかして @unchama

2023-03-13 11:07 UTC, unchama commented on terraform/onp_cluster_secrets.tf
> +    "deploy-key"  = var.newrelic_pixie_chart_deploy_key
これね〜`deploy-key`だけhelm-chart上でハードコードされてて変えられないんですよね
https://github.com/pixie-io/pixie/blob/5a7444d8c5eeb2565f9421b653a9cfd60e987624/k8s/operator/helm/values.yaml#L31-L33

2023-03-14 01:34 UTC, inductor commented on terraform/onp_cluster_secrets.tf
> +    "deploy-key"  = var.newrelic_pixie_chart_deploy_key
コメントに書かないとわからんので書いといてほしいかも

2023-03-14 14:52 UTC, unchama commented on terraform/onp_cluster_secrets.tf
> +    "deploy-key"  = var.newrelic_pixie_chart_deploy_key
書きました！！！

2023-03-14 16:19 UTC, unchama commented
OKになりました

2023-03-14 23:31 UTC, inductor approved these changes

2023-03-14 23:31 UTC, merged